<template>
	<div class="loading">
		<div class="loadingio-spinner-rolling-bpoy8a6ubgg">
			<div class="ldio-gp72cfqo7rn">
				<div></div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	name: "loading",
	data() {
		return {};
	},
};
</script>

<style type="text/css">
.loading {
	position: fixed;
	top: 0;
	bottom: 0;
	left: 0;
	right: 0;
	z-index: 99;
	opacity: 0;
	visibility: hidden;
	transition: all 0.2s ease;
	background-color: rgb(0 0 0 / 30%);
}
.loading.show {
	opacity: 1;
	visibility: visible;
}
.loading .loadingio-spinner-rolling-bpoy8a6ubgg {
	position: fixed;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
}
@keyframes ldio-gp72cfqo7rn {
	0% {
		transform: translate(-50%, -50%) rotate(0deg);
	}
	100% {
		transform: translate(-50%, -50%) rotate(360deg);
	}
}
.ldio-gp72cfqo7rn div {
	position: absolute;
	width: 60px;
	height: 60px;
	border: 10px solid #42c3c9;
	border-top-color: transparent;
	border-radius: 50%;
}
.ldio-gp72cfqo7rn div {
	animation: ldio-gp72cfqo7rn 1s linear infinite;
	top: 50px;
	left: 50px;
}
.loadingio-spinner-rolling-bpoy8a6ubgg {
	width: 90px;
	height: 90px;
	display: inline-block;
	overflow: hidden;
}
.ldio-gp72cfqo7rn {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(0.9);
	backface-visibility: hidden;
	transform-origin: 0 0; /* see note above */
}
.ldio-gp72cfqo7rn div {
	box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>